import { GoogleGenAI, Modality } from '@google/genai';

export async function generateFantasyImage(base64ImageData: string): Promise<string> {
    const ai = new GoogleGenAI({apiKey: process.env.API_KEY});

    const imagePart = {
      inlineData: {
        data: base64ImageData,
        mimeType: 'image/png',
      },
    };

    const textPart = {
      text: 'Please redraw this rough sketch in a beautiful, high-quality, detailed, epic fantasy art style. Make it look like a professional digital painting, enhancing the concept with creative details.',
    };

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [imagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return part.inlineData.data;
        }
    }
    
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error('Error generating image with Gemini:', error);
    throw new Error('Failed to generate fantasy image. Please check your API key and try again.');
  }
}
